name: Renovate
on:
  schedule:
    # Run Renovate every day at 1:00 AM
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41.0.21
        with:
          renovate-version: 38.59.2
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: renovate.json
        env:
          GITHUB_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          NPM_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          LOG_LEVEL: debug
          RENOVATE_BASE_BRANCHES: 'master,develop'
          RENOVATE_REPOSITORY_CACHE: enabled
          RENOVATE_ONBOARDING: 'false'
          RENOVATE_PLATFORM: github
          RENOVATE_ENDPOINT: ${{ secrets.GITHUB_API_URL }}
          RENOVATE_AUTODISCOVER_FILTER: ${{ github.event.repository.full_name }}
